const fs = require('fs');

const fallbackData = `
        { eventName: 'CES 2026', shortName: 'CES', category: 'Consumer Electronics', city: 'Las Vegas', state: 'NV', venue: 'Las Vegas Convention Center', dates: 'Jan 6 - Jan 9, 2026', month: 'January', year: 2026, officialWebsite: 'https://www.ces.tech', estimatedExhibitorsCount: 4000, exhibitors: [] },
        { eventName: 'NRF 2026: Retail\\'s Big Show', shortName: 'NRF', category: 'Retail', city: 'New York', state: 'NY', venue: 'Jacob K. Javits Convention Center', dates: 'Jan 11 - Jan 13, 2026', month: 'January', year: 2026, officialWebsite: 'https://nrfbigshow.nrf.com', estimatedExhibitorsCount: 1000, exhibitors: [] },
        { eventName: 'World of Concrete 2026', shortName: 'WOC', category: 'Construction', city: 'Las Vegas', state: 'NV', venue: 'Las Vegas Convention Center', dates: 'Jan 20 - Jan 22, 2026', month: 'January', year: 2026, officialWebsite: 'https://www.worldofconcrete.com', estimatedExhibitorsCount: 1500, exhibitors: [] },
        { eventName: 'SHOT Show 2026', shortName: 'SHOT Show', category: 'Hunting & Shooting', city: 'Las Vegas', state: 'NV', venue: 'The Venetian Expo', dates: 'Jan 20 - Jan 23, 2026', month: 'January', year: 2026, officialWebsite: 'https://shotshow.org', estimatedExhibitorsCount: 2500, exhibitors: [] },
        { eventName: 'Design & Construction Week 2026', shortName: 'DCW / IBS / KBIS', category: 'Home & Construction', city: 'Orlando', state: 'FL', venue: 'Orange County Convention Center', dates: 'Feb 10 - Feb 12, 2026', month: 'February', year: 2026, officialWebsite: 'https://www.designandconstructionweek.com', estimatedExhibitorsCount: 2000, exhibitors: [] },
        { eventName: 'HIMSS 2026', shortName: 'HIMSS', category: 'Healthcare IT', city: 'Las Vegas', state: 'NV', venue: 'The Venetian Expo', dates: 'Feb 23 - Feb 27, 2026', month: 'February', year: 2026, officialWebsite: 'https://www.himss.org/global-conference', estimatedExhibitorsCount: 1200, exhibitors: [] },
        { eventName: 'Natural Products Expo West 2026', shortName: 'Expo West', category: 'Food & Beverage', city: 'Anaheim', state: 'CA', venue: 'Anaheim Convention Center', dates: 'Mar 3 - Mar 7, 2026', month: 'March', year: 2026, officialWebsite: 'https://www.expowest.com', estimatedExhibitorsCount: 3000, exhibitors: [] },
        { eventName: 'CONEXPO-CON/AGG 2026', shortName: 'CONEXPO', category: 'Construction Equipment', city: 'Las Vegas', state: 'NV', venue: 'Las Vegas Convention Center', dates: 'Mar 3 - Mar 7, 2026', month: 'March', year: 2026, officialWebsite: 'https://www.conexpoconagg.com', estimatedExhibitorsCount: 2000, exhibitors: [] },
        { eventName: 'South by Southwest 2026', shortName: 'SXSW', category: 'Tech, Film & Music', city: 'Austin', state: 'TX', venue: 'Austin Convention Center', dates: 'Mar 13 - Mar 21, 2026', month: 'March', year: 2026, officialWebsite: 'https://www.sxsw.com', estimatedExhibitorsCount: 500, exhibitors: [] },
        { eventName: 'ProMat 2026', shortName: 'ProMat', category: 'Material Handling & Logistics', city: 'Chicago', state: 'IL', venue: 'McCormick Place', dates: 'Mar 16 - Mar 19, 2026', month: 'March', year: 2026, officialWebsite: 'https://www.promatshow.com', estimatedExhibitorsCount: 1000, exhibitors: [] },
        { eventName: 'ISC West 2026', shortName: 'ISC West', category: 'Security & Public Safety', city: 'Las Vegas', state: 'NV', venue: 'The Venetian Expo', dates: 'Mar 17 - Mar 20, 2026', month: 'March', year: 2026, officialWebsite: 'https://www.iscwest.com', estimatedExhibitorsCount: 1000, exhibitors: [] },
        { eventName: 'Global Pet Expo 2026', shortName: 'Global Pet Expo', category: 'Pet Products', city: 'Orlando', state: 'FL', venue: 'Orange County Convention Center', dates: 'Mar 25 - Mar 27, 2026', month: 'March', year: 2026, officialWebsite: 'https://www.globalpetexpo.org', estimatedExhibitorsCount: 1000, exhibitors: [] },
        { eventName: 'NAB Show 2026', shortName: 'NAB', category: 'Broadcasting & Media', city: 'Las Vegas', state: 'NV', venue: 'Las Vegas Convention Center', dates: 'Apr 11 - Apr 15, 2026', month: 'April', year: 2026, officialWebsite: 'https://nabshow.com', estimatedExhibitorsCount: 1500, exhibitors: [] },
        { eventName: 'RSA Conference 2026', shortName: 'RSAC', category: 'Cybersecurity', city: 'San Francisco', state: 'CA', venue: 'Moscone Center', dates: 'Apr 20 - Apr 23, 2026', month: 'April', year: 2026, officialWebsite: 'https://www.rsaconference.com', estimatedExhibitorsCount: 600, exhibitors: [] },
        { eventName: 'Offshore Technology Conference 2026', shortName: 'OTC', category: 'Energy & Offshore', city: 'Houston', state: 'TX', venue: 'NRG Park', dates: 'May 4 - May 7, 2026', month: 'May', year: 2026, officialWebsite: 'https://2026.otcnet.org', estimatedExhibitorsCount: 2000, exhibitors: [] },
        { eventName: 'National Restaurant Association Show 2026', shortName: 'NRA Show', category: 'Foodservice', city: 'Chicago', state: 'IL', venue: 'McCormick Place', dates: 'May 16 - May 19, 2026', month: 'May', year: 2026, officialWebsite: 'https://www.nationalrestaurantshow.com', estimatedExhibitorsCount: 2000, exhibitors: [] },
        { eventName: 'Sweets & Snacks Expo 2026', shortName: 'Sweets & Snacks', category: 'Confectionery & Snacks', city: 'Indianapolis', state: 'IN', venue: 'Indiana Convention Center', dates: 'May 18 - May 21, 2026', month: 'May', year: 2026, officialWebsite: 'https://sweetsandsnacks.com', estimatedExhibitorsCount: 800, exhibitors: [] },
        { eventName: 'InfoComm 2026', shortName: 'InfoComm', category: 'Pro AV & IT', city: 'Las Vegas', state: 'NV', venue: 'Las Vegas Convention Center', dates: 'Jun 6 - Jun 12, 2026', month: 'June', year: 2026, officialWebsite: 'https://www.infocommshow.org', estimatedExhibitorsCount: 1000, exhibitors: [] },
        { eventName: 'E3 2026', shortName: 'E3', category: 'Video Games', city: 'Los Angeles', state: 'CA', venue: 'Los Angeles Convention Center', dates: 'Jun 9 - Jun 11, 2026', month: 'June', year: 2026, officialWebsite: 'https://e3expo.com', estimatedExhibitorsCount: 200, exhibitors: [] },
        { eventName: 'AWFS Fair 2026', shortName: 'AWFS', category: 'Woodworking Machinery', city: 'Las Vegas', state: 'NV', venue: 'Las Vegas Convention Center', dates: 'Jul 20 - Jul 23, 2026', month: 'July', year: 2026, officialWebsite: 'https://www.awfsfair.org', estimatedExhibitorsCount: 600, exhibitors: [] },
        { eventName: 'MAGIC Las Vegas Fall 2026', shortName: 'MAGIC', category: 'Fashion & Apparel', city: 'Las Vegas', state: 'NV', venue: 'Las Vegas Convention Center', dates: 'Aug 17 - Aug 19, 2026', month: 'August', year: 2026, officialWebsite: 'https://www.magicfashionevents.com', estimatedExhibitorsCount: 1500, exhibitors: [] },
        { eventName: 'IWF 2026', shortName: 'IWF', category: 'Woodworking', city: 'Atlanta', state: 'GA', venue: 'Georgia World Congress Center', dates: 'Aug 25 - Aug 28, 2026', month: 'August', year: 2026, officialWebsite: 'https://www.iwfatlanta.com', estimatedExhibitorsCount: 1000, exhibitors: [] },
        { eventName: 'IMTS 2026', shortName: 'IMTS', category: 'Manufacturing Technology', city: 'Chicago', state: 'IL', venue: 'McCormick Place', dates: 'Sep 14 - Sep 19, 2026', month: 'September', year: 2026, officialWebsite: 'https://www.imts.com', estimatedExhibitorsCount: 2000, exhibitors: [] },
        { eventName: 'RE+, SPI & ESI 2026', shortName: 'RE+', category: 'Renewable Energy', city: 'Anaheim', state: 'CA', venue: 'Anaheim Convention Center', dates: 'Sep 14 - Sep 17, 2026', month: 'September', year: 2026, officialWebsite: 'https://www.re-plus.com', estimatedExhibitorsCount: 1200, exhibitors: [] },
        { eventName: 'PACK EXPO International 2026', shortName: 'PACK EXPO', category: 'Packaging', city: 'Chicago', state: 'IL', venue: 'McCormick Place', dates: 'Nov 8 - Nov 11, 2026', month: 'November', year: 2026, officialWebsite: 'https://www.packexpointernational.com', estimatedExhibitorsCount: 2500, exhibitors: [] },
        { eventName: 'SEMA Show 2026', shortName: 'SEMA', category: 'Automotive Aftermarket', city: 'Las Vegas', state: 'NV', venue: 'Las Vegas Convention Center', dates: 'Nov 3 - Nov 6, 2026', month: 'November', year: 2026, officialWebsite: 'https://www.semashow.com', estimatedExhibitorsCount: 2400, exhibitors: [] },
        { eventName: 'AAPEX 2026', shortName: 'AAPEX', category: 'Automotive Aftermarket', city: 'Las Vegas', state: 'NV', venue: 'The Venetian Expo', dates: 'Nov 3 - Nov 5, 2026', month: 'November', year: 2026, officialWebsite: 'https://www.aapexshow.com', estimatedExhibitorsCount: 2500, exhibitors: [] },
        { eventName: 'FABTECH 2026', shortName: 'FABTECH', category: 'Metal Forming & Welding', city: 'Las Vegas', state: 'NV', venue: 'Las Vegas Convention Center', dates: 'Nov 18 - Nov 20, 2026', month: 'November', year: 2026, officialWebsite: 'https://www.fabtechexpo.com', estimatedExhibitorsCount: 1500, exhibitors: [] },
        { eventName: 'RSNA 2026', shortName: 'RSNA', category: 'Medical/Radiology', city: 'Chicago', state: 'IL', venue: 'McCormick Place', dates: 'Nov 29 - Dec 3, 2026', month: 'November', year: 2026, officialWebsite: 'https://www.rsna.org', estimatedExhibitorsCount: 700, exhibitors: [] },
        { eventName: 'IAAPA Expo 2026', shortName: 'IAAPA', category: 'Amusement & Attractions', city: 'Orlando', state: 'FL', venue: 'Orange County Convention Center', dates: 'Nov 17 - Nov 20, 2026', month: 'November', year: 2026, officialWebsite: 'https://www.iaapa.org/expos/iaapa-expo', estimatedExhibitorsCount: 1000, exhibitors: [] },
        { eventName: 'PowerGen International 2026', shortName: 'PowerGen', category: 'Power Generation', city: 'Dallas', state: 'TX', venue: 'Kay Bailey Hutchison Convention Center', dates: 'Dec 8 - Dec 10, 2026', month: 'December', year: 2026, officialWebsite: 'https://www.powergen.com', estimatedExhibitorsCount: 800, exhibitors: [] }
`;

let code = fs.readFileSync('server.ts', 'utf8');

const startStr = "extractedEvents = [";
const endStr = "      ];";
const startIdx = code.lastIndexOf(startStr, code.indexOf('// 2.5 Live Exact Trade Show Search & Extraction via Gemini Google Search Grounding'));
const endIdx = code.indexOf(endStr, startIdx);

if (startIdx !== -1 && endIdx !== -1) {
    const newCode = code.substring(0, startIdx) + "extractedEvents = [" + fallbackData + code.substring(endIdx);
    fs.writeFileSync('server.ts', newCode);
    console.log("Updated fallback shows");
} else {
    console.log("Could not find array to replace");
}

